module ScoreTags exposing (..)

ones = "Ones"
twos ="Twos"
threes ="Threes"
fours = "Fours"
fives = "Fives"
sixes = "Sixes"
upperTotal = "Total"
bonus = "Bonus"
threeOfAKind = "3 of a kind"
fourOfAKind = "4 of a kind"
fullHouse = "Full House"
smallStraight = "Sm Straight"
largeStraight = "Lg Straight"
fiveOfAKind = "5 of a kind"
chance = "Chance"
total = "Total Score"
weighted = "Weighted Score"
grandTotal = "Grand Total"
